import { DayOfWeek, Meal, Workout } from "../types";

export const MOCK_MEALS: Meal[] = [
  {
    id: "1",
    name: "Desjejum",
    type: "breakfast",
    time: "05:45",
    description: "Refeição da manhã para começar o dia com energia",
    foods: [
      {
        id: "1",
        name: "Pão integral",
        portion: "2 fatias",
        calories: 160,
        proteins: 6,
        carbs: 28,
        fats: 2,
      },
      {
        id: "2",
        name: "Creme de ricota light",
        portion: "1 colher (sopa)",
        calories: 45,
        proteins: 4,
        carbs: 1,
        fats: 3,
      },
      {
        id: "3",
        name: "Leite desnatado com café",
        portion: "1 xícara (200ml)",
        calories: 90,
        proteins: 8,
        carbs: 12,
        fats: 0.5,
      },
    ],
  },
  {
    id: "2",
    name: "Pós-treino",
    type: "post-workout",
    time: "07:50",
    description: "Reposição proteica após o treino",
    foods: [
      {
        id: "4",
        name: "Whey protein com água",
        portion: "1 scoop (30g)",
        calories: 120,
        proteins: 24,
        carbs: 3,
        fats: 2,
      },
    ],
  },
  {
    id: "3",
    name: "Colação",
    type: "snack",
    time: "09:30",
    description: "Lanche da manhã para manter o metabolismo ativo",
    foods: [
      {
        id: "5",
        name: "Maçã",
        portion: "1 unidade média",
        calories: 72,
        proteins: 0.4,
        carbs: 19,
        fats: 0.2,
      },
    ],
  },
  {
    id: "4",
    name: "Almoço",
    type: "lunch",
    time: "12:00",
    description: "Refeição principal do dia com todos os macronutrientes",
    foods: [
      {
        id: "6",
        name: "Arroz integral",
        portion: "4 colheres (sopa)",
        calories: 160,
        proteins: 4,
        carbs: 35,
        fats: 1,
      },
      {
        id: "7",
        name: "Feijão",
        portion: "1 concha pequena",
        calories: 110,
        proteins: 7,
        carbs: 20,
        fats: 0.5,
      },
      {
        id: "8",
        name: "Filé de frango grelhado",
        portion: "120g",
        calories: 165,
        proteins: 31,
        carbs: 0,
        fats: 3.5,
      },
      {
        id: "9",
        name: "Batata doce",
        portion: "1 unidade pequena",
        calories: 120,
        proteins: 2,
        carbs: 28,
        fats: 0.1,
      },
      {
        id: "10",
        name: "Salada de folhas verdes",
        portion: "1 prato",
        calories: 25,
        proteins: 1,
        carbs: 5,
        fats: 0,
      },
    ],
  },
  {
    id: "5",
    name: "Lanche da Tarde",
    type: "afternoon-snack",
    time: "15:30",
    description: "Lanche intermediário para manter a energia",
    foods: [
      {
        id: "11",
        name: "Iogurte natural",
        portion: "1 pote (170g)",
        calories: 100,
        proteins: 6,
        carbs: 12,
        fats: 2.6,
      },
      {
        id: "12",
        name: "Granola",
        portion: "1 colher (sopa)",
        calories: 70,
        proteins: 2,
        carbs: 12,
        fats: 3,
      },
    ],
  },
  {
    id: "6",
    name: "Jantar",
    type: "dinner",
    time: "17:35",
    description: "Refeição noturna mais leve que o almoço",
    foods: [
      {
        id: "13",
        name: "Arroz integral",
        portion: "3 colheres (sopa)",
        calories: 120,
        proteins: 3,
        carbs: 26,
        fats: 0.8,
      },
      {
        id: "14",
        name: "Filé de peixe",
        portion: "120g",
        calories: 140,
        proteins: 28,
        carbs: 0,
        fats: 3,
      },
      {
        id: "15",
        name: "Legumes no vapor",
        portion: "1/2 prato",
        calories: 70,
        proteins: 2,
        carbs: 15,
        fats: 0.5,
      },
    ],
  },
  {
    id: "7",
    name: "Ceia",
    type: "supper",
    time: "20:30",
    description: "Pequena refeição antes de dormir",
    foods: [
      {
        id: "16",
        name: "Banana",
        portion: "1 unidade média",
        calories: 105,
        proteins: 1.3,
        carbs: 27,
        fats: 0.4,
      },
    ],
  },
];

export const MOCK_WORKOUTS: Record<DayOfWeek, Workout> = {
  monday: {
    id: "1",
    day: "monday",
    muscleGroups: ["Peito", "Tríceps"],
    description: "Treino focado em desenvolvimento de peito e tríceps",
    exercises: [
      {
        id: "1",
        name: "Supino Reto",
        description: "Com barra",
        sets: 4,
        reps: "10-12",
        restTime: 90,
      },
      {
        id: "2",
        name: "Supino Inclinado",
        description: "Com halteres",
        sets: 4,
        reps: "10-12",
        restTime: 90,
      },
      {
        id: "3",
        name: "Crossover",
        description: "No cabo",
        sets: 3,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "4",
        name: "Tríceps Corda",
        description: "No cabo",
        sets: 4,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "5",
        name: "Tríceps Francês",
        description: "Com halteres",
        sets: 3,
        reps: "10-12",
        restTime: 60,
      },
      {
        id: "6",
        name: "Mergulho no banco",
        description: "Peso corporal",
        sets: 3,
        reps: "Falha",
        restTime: 60,
      },
    ],
  },
  tuesday: {
    id: "2",
    day: "tuesday",
    muscleGroups: ["Pernas"],
    description: "Treino completo para desenvolvimento das pernas",
    exercises: [
      {
        id: "7",
        name: "Agachamento",
        description: "Com barra",
        sets: 4,
        reps: "10-12",
        restTime: 120,
      },
      {
        id: "8",
        name: "Leg Press",
        description: "Máquina",
        sets: 4,
        reps: "12-15",
        restTime: 90,
      },
      {
        id: "9",
        name: "Cadeira Extensora",
        description: "Máquina",
        sets: 3,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "10",
        name: "Cadeira Flexora",
        description: "Máquina",
        sets: 3,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "11",
        name: "Panturrilha em Pé",
        description: "Máquina",
        sets: 4,
        reps: "15-20",
        restTime: 45,
      },
      {
        id: "12",
        name: "Avanço",
        description: "Com halteres",
        sets: 3,
        reps: "10 por perna",
        restTime: 60,
      },
    ],
  },
  wednesday: {
    id: "3",
    day: "wednesday",
    muscleGroups: ["Costas", "Bíceps"],
    description: "Treino focado em desenvolvimento de costas e bíceps",
    exercises: [
      {
        id: "13",
        name: "Puxada Frontal",
        description: "No cabo",
        sets: 4,
        reps: "10-12",
        restTime: 90,
      },
      {
        id: "14",
        name: "Remada Curvada",
        description: "Com barra",
        sets: 4,
        reps: "10-12",
        restTime: 90,
      },
      {
        id: "15",
        name: "Remada Unilateral",
        description: "Com halter",
        sets: 3,
        reps: "10-12 por braço",
        restTime: 60,
      },
      {
        id: "16",
        name: "Rosca Direta",
        description: "Com barra W",
        sets: 4,
        reps: "10-12",
        restTime: 60,
      },
      {
        id: "17",
        name: "Rosca Alternada",
        description: "Com halteres",
        sets: 3,
        reps: "10-12",
        restTime: 60,
      },
      {
        id: "18",
        name: "Rosca Concentrada",
        description: "Com halter",
        sets: 3,
        reps: "10-12 por braço",
        restTime: 60,
      },
    ],
  },
  thursday: {
    id: "4",
    day: "thursday",
    muscleGroups: ["Ombros", "Abdômen"],
    description: "Treino focado em desenvolvimento de ombros e abdominais",
    exercises: [
      {
        id: "19",
        name: "Desenvolvimento",
        description: "Com halteres",
        sets: 4,
        reps: "10-12",
        restTime: 90,
      },
      {
        id: "20",
        name: "Elevação Lateral",
        description: "Com halteres",
        sets: 4,
        reps: "10-12",
        restTime: 60,
      },
      {
        id: "21",
        name: "Elevação Frontal",
        description: "Com halteres",
        sets: 3,
        reps: "10-12",
        restTime: 60,
      },
      {
        id: "22",
        name: "Crunch",
        description: "No solo",
        sets: 3,
        reps: "15-20",
        restTime: 45,
      },
      {
        id: "23",
        name: "Prancha",
        description: "Isometria",
        sets: 3,
        reps: "30-60 segundos",
        restTime: 45,
      },
      {
        id: "24",
        name: "Abdominal Infra",
        description: "Com elevação de pernas",
        sets: 3,
        reps: "12-15",
        restTime: 45,
      },
    ],
  },
  friday: {
    id: "5",
    day: "friday",
    muscleGroups: ["Full Body"],
    description: "Treino completo para todos os grupos musculares",
    exercises: [
      {
        id: "25",
        name: "Agachamento",
        description: "Com barra",
        sets: 3,
        reps: "12-15",
        restTime: 90,
      },
      {
        id: "26",
        name: "Supino Reto",
        description: "Com barra",
        sets: 3,
        reps: "12-15",
        restTime: 90,
      },
      {
        id: "27",
        name: "Remada Baixa",
        description: "No cabo",
        sets: 3,
        reps: "12-15",
        restTime: 90,
      },
      {
        id: "28",
        name: "Desenvolvimento",
        description: "Com barra",
        sets: 3,
        reps: "12-15",
        restTime: 90,
      },
      {
        id: "29",
        name: "Rosca Direta",
        description: "Com barra",
        sets: 3,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "30",
        name: "Tríceps Corda",
        description: "No cabo",
        sets: 3,
        reps: "12-15",
        restTime: 60,
      },
      {
        id: "31",
        name: "Prancha",
        description: "Isometria",
        sets: 3,
        reps: "30-60 segundos",
        restTime: 45,
      },
    ],
  },
  saturday: {
    id: "6",
    day: "saturday",
    muscleGroups: ["Descanso"],
    description: "Dia de recuperação e descanso",
    exercises: [],
  },
  sunday: {
    id: "7",
    day: "sunday",
    muscleGroups: ["Descanso"],
    description: "Dia de recuperação e descanso",
    exercises: [],
  },
};
